on:
  pull_request:
    types: 
      - opened
      - synchronize
      - reopened
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build:
    # We'll dynamically set runs-on based on the OS in the matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.8, 3.9]
    steps:
      - name: Check OS and Python
        run: echo "Running on OS = ${{ matrix.os }} with Python ${{ matrix.python-version }}"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          echo "Dependencies installed"

      - name: PR step
        run: echo "This runs for a pull request or manual dispatch."
